github: enesorhann          # GitHub Sponsors 
ko_fi: enesorhann              # Ko-fi 
buy_me_a_coffee: enesorhann    # Buy Me a Coffee 
patreon:                       
open_collective:                 
tidelift:                       
community_bridge:               
liberapay:                       
issuehunt:                       
lfx_crowdfunding:               
polar:                           
thanks_dev:                      
custom: []   
