// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA24-WSRi8--kFxbSx4t5CEnntTELsbnYI',
    appId: '1:555554166483:web:5dc00ade5be1f1298aa626',
    messagingSenderId: '555554166483',
    projectId: 'donemprojesi-2c535',
    authDomain: 'donemprojesi-2c535.firebaseapp.com',
    storageBucket: 'donemprojesi-2c535.firebasestorage.app',
    measurementId: 'G-97XT188G4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCocPIqobexkj__rJZhDEjbz4I1uIjtuXg',
    appId: '1:555554166483:android:191268a9b2888de18aa626',
    messagingSenderId: '555554166483',
    projectId: 'donemprojesi-2c535',
    storageBucket: 'donemprojesi-2c535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZCcFUI0jvcpCasdS-akRhAGoGWBpZ9Y',
    appId: '1:555554166483:ios:36a6d027ebcd62d78aa626',
    messagingSenderId: '555554166483',
    projectId: 'donemprojesi-2c535',
    storageBucket: 'donemprojesi-2c535.firebasestorage.app',
    iosBundleId: 'com.enesorhan.depManagerPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZCcFUI0jvcpCasdS-akRhAGoGWBpZ9Y',
    appId: '1:555554166483:ios:36a6d027ebcd62d78aa626',
    messagingSenderId: '555554166483',
    projectId: 'donemprojesi-2c535',
    storageBucket: 'donemprojesi-2c535.firebasestorage.app',
    iosBundleId: 'com.enesorhan.depManagerPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA24-WSRi8--kFxbSx4t5CEnntTELsbnYI',
    appId: '1:555554166483:web:29e905690d2769698aa626',
    messagingSenderId: '555554166483',
    projectId: 'donemprojesi-2c535',
    authDomain: 'donemprojesi-2c535.firebaseapp.com',
    storageBucket: 'donemprojesi-2c535.firebasestorage.app',
    measurementId: 'G-X9VPSLMWTL',
  );
}
